name: Deploy Cloud Function

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '.git/**'
      - 'readme.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/setup-gcloud@v0
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy Cloud Function
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: webhook
          runtime: nodejs20
          entrypoint: index.js
          trigger: http
          region: asia-southeast2